version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: wedding_db
      POSTGRES_USER: wedding_user
      POSTGRES_PASSWORD: wedding_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: