#name: Deploy
#
#on:
#  push:
#    branches: [ main ]
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build  # This ensures deploy only runs after successful build
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Build JAR
#        run: ./gradlew buildFatJar
#
#      # We'll add actual deployment steps later when we have a server
#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: jar-file
#          path: build/libs/*.jar